### ISSUE TITLE
Blanck page after fresh install

### ISSUE THREAD

**Issue by sandrosousa** [salesagility/SuiteCRM-Core#1]
#### Issue

Blanck page after fresh install
#### Expected Behavior

Login page
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 8-Beta1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Chrome
* Environment name and version: MySQL, PHP 7
* Operating System and version : Debian

**Comment by sandrosousa** [comment]
console have this js error:
![image](https://user-images.githubusercontent.com/19153579/113322151-3f8c9300-930c-11eb-9c76-7f76de0be237.png)

**Comment by clemente-raposo** [comment]
Hi @sandrosousa,

Thank you for trying out SuiteCRM 8 beta and for your feedback

I imagine you've downloaded the zip from the link [SuiteCrm 8 beta preview](https://suitecrm.com/suitecrm-8-beta-preview/) page.

And used the install command `./bin/console suitecrm:app:install` and followed other steps on [SuiteCRM 8 admin guide](https://docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing/)

In order to help understand your problem, could you provide a bit more information about your environment:

- what php version are you using: 7.3? 7.4?
- what webserver are you using and the version? apache?

That error is most likely thrown due to an error on a call to the backed.

On the chrome network tab you you'll see some `graphql` calls like the following:

![image](https://user-images.githubusercontent.com/1140849/113326575-c1cb8600-9311-11eb-900d-95532bc4a02f.png)


Could you check if there are any errors on the graphql calls by checking the response on the preview tab. If so could you send that info please? (the response should looks something like the following)

![image](https://user-images.githubusercontent.com/1140849/113326979-48806300-9312-11eb-896e-36f1d3917135.png)

Thank you.

**Comment by sandrosousa** [comment]
Hi @clemente-raposo 

I think I dont have graphql, I have this error:
![image](https://user-images.githubusercontent.com/19153579/113328704-94340c00-9314-11eb-998d-addde843ea7d.png)

**Comment by clemente-raposo** [comment]
Hi @sandrosousa,

Thats exactly it, I see you have a 404. On the preview tab for that request do you have any data?

By the way regarding the `graphql` it now comes with SuiteCRM 8 backend.

**Comment by sandrosousa** [comment]
Hi @clemente-raposo 
In preview I have Page not found error.

![image](https://user-images.githubusercontent.com/19153579/113331375-d01ca080-9317-11eb-9a69-cb3cee6d6de5.png)

**Comment by clemente-raposo** [comment]
Hi @sandrosousa,

Thank you. The 404 leads me to think that the webserver may not be allowing re-writes.

Could you check if your apache configuration is allowing for re-writes?

if the mod_rewrite is enabled and the vhost config is allowing it.

Take the following example of an apache vhost configuration (not complete):
```
<VirtualHost *:80>
    ServerName domain.tld
    ServerAlias www.domain.tld

    DocumentRoot /var/www/project/public
    <Directory /var/www/project/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>
    
    
```

**Comment by clemente-raposo** [comment]
Regarding the above one thing you could to check if its a rewrite problem  is:

Try doing a request to `https://<your_host>/index.php/api/graphql`. If you get an error message like the following and not a 404 it means its a problem with the rewrite.

![image](https://user-images.githubusercontent.com/1140849/113334155-44a50e80-931b-11eb-8381-872d06b04d0f.png)

**Comment by sandrosousa** [comment]
@clemente-raposo I delete the database and the install dir and try to reinstall again but now I get this error:

![image](https://user-images.githubusercontent.com/19153579/113344329-d36c5800-9328-11eb-91e2-4a1afbe34e63.png)

**Comment by mattlorimer** [comment]
Remove the .env.local.php file in the root directory to run the install again

**Comment by sandrosousa** [comment]
@mattlorimer thanks, it worked!
@clemente-raposo after reinstallation the login page shows up correctly, already login successfully, I'm going to start exploring this version, thanks!
