### ISSUE TITLE
Possible typo in boostrap.php

### ISSUE THREAD

**Issue by websoftix** [salesagility/SuiteCRM-Core#3]
Trying to install SuiteCRM8 from Github sources and having a few difficulties I was looking trough some of the files and I think I found a typo in bootstrap.php, there is "absrtact" which should probably be "abstract". It's not related to any issue I've had but I though it's worth reporting it:

https://github.com/salesagility/SuiteCRM-Core/blob/10ad06e4509bf733dd65d56fc4c9431da38c59ea/config/bootstrap.php#L49

**Comment by clemente-raposo** [comment]
Hi @websoftix ,

Thank you for trying out SuiteCRM 8 beta. And also thank you for your feedback.

We will have a look at it. I think its not even required any longer, though I need to double check. 
@Dillon-Brown think we need to have another look at this.

By the way, what issues are you having when trying to install? if you could create a forum post like `'SuiteCRM 8 install steps'` (or similar) it would probably be ideal, as it could help other people also.

Again thank you for your feedback.

**Comment by Dillon-Brown** [comment]
Hi @websoftix, thanks for the report. This is indeed a typo but it's actually with the legacy Suite-7 project. The real problem here is that there are areas in the legacy codebase with broken docblock references like this: 

https://github.com/salesagility/SuiteCRM/blob/master/include/database/DBManager.php#L194

```
    /**
     * Driver name label, for install
     * @absrtact
     * @var string
     */
    public $label = '';
```

Which when read from the Suite-8 legacy handlers, cause doctrine to break. This is more of a temporary "hack" with these three ignores solving 99% of the problems I was having when using doctrine in Suite-8 with Suite-7 bootstrapped. I imagine we'll need to revisit this at some point in the future, perhaps looking at a way to have doctrine ignore annotations that path into legacy, etc.
